export const dictIcon = {
    "alt": {
        "0": "Sunny",
        "1": "Slightly cloudy",
        "2": "Hazy sky",
        "3": "Cloudy",
        "4": "Very cloudy",
        "5": "Covered",
        "6": "Fog",
        "7": "Freezing fog",
        "10": "Light rain",
        "11": "Moderate rain",
        "12": "Heavy rain",
        "13": "Light freezing rain",
        "14": "Moderate freezing rain",
        "15": "Heavy freezing rain",
        "16": "Drizzle",
        "20": "Light snow",
        "21": "Moderate snow",
        "22": "Heavy snow",
        "30": "Low mixed rain and snow",
        "31": "Moderate mixed rain and snow",
        "32": "Heavy mixed rain and snow",
        "40": "Local and light rain showers",
        "41": "Local rain showers",
        "42": "Local and heavy showers",
        "43": "Light rain showers",
        "44": "Rain showers",
        "45": "Heavy rain showers",
        "46": "Light and frequent rain showers",
        "47": "Frequent rain showers",
        "48": "Heavy and frequent rain showers",
        "60": "Localized and light snow showers",
        "61": "Localized snow showers",
        "62": "Localized and heavy snow showers",
        "63": "Light snow showers",
        "64": "Snow showers",
        "65": "Heavy snow showers",
        "66": "Light and frequent snow showers",
        "67": "Frequent snow showers",
        "68": "Heavy and frequent snow showers",
        "70": "Localized and light mixed rain and snow showers",
        "71": "Localized mixed rain and snow showers",
        "72": "Localized and heavy mixed rain and snow showers",
        "73": "Light mixed rain and snow showers",
        "74": "Mixed rain and snow showers",
        "75": "Heavy mixed rain and snow showers",
        "76": "Light and numerous mixed rain and snow showers",
        "77": "Frequent mixed rain and snow showers",
        "78": "Heavy and frequent mixed rain and snow showers",
        "100": "Weak and local thunderstorms",
        "101": "Local thunderstorms",
        "102": "Strong and local thunderstorms",
        "103": "Weak thunderstorms",
        "104": "Thunderstorms",
        "105": "Strong thunderstorms",
        "106": "Weak and frequent thunderstorms",
        "107": "Frequent thunderstorms",
        "108": "Strong and frequent thunderstorms",
        "120": "Local light thunderstorms with snow or sleet",
        "121": "Local storms of snow or sleet",
        "122": "Strong and local storms of snow or sleet",
        "123": "Light thunderstorms of snow or sleet",
        "124": "Snowstorms or sleet",
        "125": "Heavy thunderstorms with snow or sleet",
        "126": "Light and frequent thunderstorms of snow or sleet",
        "127": "Frequent storms of snow or sleet",
        "128": "Strong and frequent storms of snow or sleet",
        "130": "Weak, local thunderstorms of mixed rain and snow or sleet",
        "131": "Local thunderstorms of mixed rain and snow or sleet",
        "132": "Strong and local thunderstorms of mixed rain and snow or sleet",
        "133": "Light thunderstorms of mixed rain and snow or sleet",
        "134": "Mixed rain and snow storms or sleet",
        "135": "Strong thunderstorms of mixed rain and snow or sleet",
        "136": "Weak and frequent thunderstorms of mixed rain and snow or sleet",
        "137": "Frequent storms of mixed rain and snow or sleet",
        "138": "Strong and frequent thunderstorms of mixed rain and snow or sleet",
        "140": "Stormy rain",
        "141": "Rain and snow mixed with storminess",
        "142": "Snow with a stormy character",
        "210": "Intermittent light rain",
        "211": "Intermittent moderate rain",
        "212": "Intermittent heavy rain",
        "220": "Intermittent light snow",
        "221": "Intermittent moderate snow",
        "222": "Intermittent heavy snow",
        "230": "Low mixed rain and snow",
        "231": "Moderate mixed rain and snow",
        "232": "Heavy mixed rain and snow",
        "235": "Hail showers"
    },
    "dayIcon": {
        "0": "clear-day.svg",
        "1": "partly-cloudy-day.svg",
        "2": "partly-cloudy-day.svg",
        "3": "overcast-day.svg",
        "4": "extreme-day.svg",
        "5": "extreme.svg",
        "6": "fog-day.svg",
        "7": "overcast-day-fog.svg",
        "10": "partly-cloudy-day-drizzle.svg",
        "11": "overcast-day-rain.svg",
        "12": "extreme-rain.svg",
        "13": "partly-cloudy-day-sleet.svg",
        "14": "overcast-day-sleet.svg",
        "15": "extreme-sleet.svg",
        "16": "partly-cloudy-day-drizzle.svg",
        "20": "partly-cloudy-day-snow.svg",
        "21": "overcast-day-snow.svg",
        "22": "extreme-snow.svg",
        "30": "partly-cloudy-day-sleet.svg",
        "31": "overcast-day-sleet.svg",
        "32": "extreme-sleet.svg",
        "40": "partly-cloudy-day-drizzle.svg",
        "41": "overcast-day-rain.svg",
        "42": "extreme-day-rain.svg",
        "43": "partly-cloudy-day-drizzle.svg",
        "44": "overcast-day-rain.svg",
        "45": "extreme-day-rain.svg",
        "46": "partly-cloudy-day-drizzle.svg",
        "47": "overcast-day-rain.svg",
        "48": "extreme-day-rain.svg",
        "60": "partly-cloudy-day-snow.svg",
        "61": "overcast-day-snow.svg",
        "62": "extreme-day-snow.svg",
        "63": "partly-cloudy-day-snow.svg",
        "64": "overcast-day-snow.svg",
        "65": "extreme-snow.svg",
        "66": "partly-cloudy-day-snow.svg",
        "67": "overcast-day-snow.svg",
        "68": "extreme-snow.svg",
        "70": "partly-cloudy-day-sleet.svg",
        "71": "overcast-day-sleet.svg",
        "72": "extreme-day-sleet.svg",
        "73": "partly-cloudy-day-sleet.svg",
        "74": "overcast-day-sleet.svg",
        "75": "extreme-sleet.svg",
        "76": "partly-cloudy-day-sleet.svg",
        "77": "overcast-day-sleet.svg",
        "78": "extreme-sleet.svg",
        "100": "thunderstorms-day.svg",
        "101": "thunderstorms-day-overcast.svg",
        "102": "thunderstorms-day-extreme.svg",
        "103": "thunderstorms-day.svg",
        "104": "thunderstorms.svg",
        "105": "thunderstorms-extreme.svg",
        "106": "thunderstorms-day-overcast.svg",
        "107": "thunderstorms-overcast.svg",
        "108": "thunderstorms-extreme.svg",
        "120": "thunderstorms-day-snow.svg",
        "121": "thunderstorms-day-overcast-snow.svg",
        "122": "thunderstorms-day-extreme-snow.svg",
        "123": "thunderstorms-day-snow.svg",
        "124": "thunderstorms-snow.svg",
        "125": "thunderstorms-extreme-snow.svg",
        "126": "thunderstorms-day-overcast-snow.svg",
        "127": "thunderstorms-overcast-snow.svg",
        "128": "thunderstorms-extreme-snow.svg",
        "130": "thunderstorms-day-overcast-rain.svg",
        "131": "thunderstorms-day-extreme-rain.svg",
        "132": "thunderstorms-extreme-rain.svg",
        "133": "thunderstorms-day-snow.svg",
        "134": "thunderstorms-snow.svg",
        "135": "thunderstorms-extreme-snow.svg",
        "136": "thunderstorms-day-snow.svg",
        "137": "thunderstorms-snow.svg",
        "138": "thunderstorms-extreme-snow.svg",
        "140": "thunderstorms-rain.svg",
        "141": "thunderstorms-day-overcast-snow.svg",
        "142": "thunderstorms-extreme-snow.svg",
        "210": "partly-cloudy-day-rain.svg",
        "211": "overcast-day-rain.svg",
        "212": "extreme-day-rain.svg",
        "220": "partly-cloudy-day-snow.svg",
        "221": "overcast-day-snow.svg",
        "222": "extreme-night-snow.svg",
        "230": "partly-cloudy-day-snow.svg",
        "231": "overcast-day-snow.svg",
        "232": "extreme-night-snow.svg",
        "235": "extreme-day-hail.svg"
    },
    "nightIcon": {
        "0": "clear-night.svg",
        "1": "clear-night.svg",
        "2": "partly-cloudy-night.svg",
        "3": "overcast-night.svg",
        "4": "extreme-night.svg",
        "5": "extreme.svg",
        "6": "fog-night.svg",
        "7": "overcast-night-fog.svg",
        "10": "partly-cloudy-night-drizzle.svg",
        "11": "overcast-night-rain.svg",
        "12": "extreme-rain.svg",
        "13": "partly-cloudy-night-sleet.svg",
        "14": "overcast-night-sleet.svg",
        "15": "extreme-sleet.svg",
        "16": "partly-cloudy-night-drizzle.svg",
        "20": "partly-cloudy-night-snow.svg",
        "21": "overcast-night-snow.svg",
        "22": "extreme-snow.svg",
        "30": "partly-cloudy-night-sleet.svg",
        "31": "overcast-night-sleet.svg",
        "32": "extreme-sleet.svg",
        "40": "partly-cloudy-night-drizzle.svg",
        "41": "overcast-night-rain.svg",
        "42": "extreme-night-rain.svg",
        "43": "partly-cloudy-night-drizzle.svg",
        "44": "overcast-night-rain.svg",
        "45": "extreme-night-rain.svg",
        "46": "partly-cloudy-night-drizzle.svg",
        "47": "overcast-night-rain.svg",
        "48": "extreme-night-rain.svg",
        "60": "partly-cloudy-night-snow.svg",
        "61": "overcast-night-snow.svg",
        "62": "extreme-night-snow.svg",
        "63": "partly-cloudy-night-snow.svg",
        "64": "overcast-night-snow.svg",
        "65": "extreme-snow.svg",
        "66": "partly-cloudy-night-snow.svg",
        "67": "overcast-night-snow.svg",
        "68": "extreme-snow.svg",
        "70": "partly-cloudy-night-sleet.svg",
        "71": "overcast-night-sleet.svg",
        "72": "extreme-night-sleet.svg",
        "73": "partly-cloudy-night-sleet.svg",
        "74": "overcast-night-sleet.svg",
        "75": "extreme-sleet.svg",
        "76": "partly-cloudy-night-sleet.svg",
        "77": "overcast-night-sleet.svg",
        "78": "extreme-sleet.svg",
        "100": "thunderstorms-night.svg",
        "101": "thunderstorms-night-overcast.svg",
        "102": "thunderstorms-night-extreme.svg",
        "103": "thunderstorms-night.svg",
        "104": "thunderstorms.svg",
        "105": "thunderstorms-extreme.svg",
        "106": "thunderstorms-night-overcast.svg",
        "107": "thunderstorms-overcast.svg",
        "108": "thunderstorms-extreme.svg",
        "120": "thunderstorms-night-snow.svg",
        "121": "thunderstorms-night-overcast-snow.svg",
        "122": "thunderstorms-night-extreme-snow.svg",
        "123": "thunderstorms-night-snow.svg",
        "124": "thunderstorms-snow.svg",
        "125": "thunderstorms-extreme-snow.svg",
        "126": "thunderstorms-night-overcast-snow.svg",
        "127": "thunderstorms-overcast-snow.svg",
        "128": "thunderstorms-extreme-snow.svg",
        "130": "thunderstorms-night-overcast-rain.svg",
        "131": "thunderstorms-night-extreme-rain.svg",
        "132": "thunderstorms-extreme-rain.svg",
        "133": "thunderstorms-night-snow.svg",
        "134": "thunderstorms-snow.svg",
        "135": "thunderstorms-extreme-snow.svg",
        "136": "thunderstorms-night-snow.svg",
        "137": "thunderstorms-snow.svg",
        "138": "thunderstorms-extreme-snow.svg",
        "140": "thunderstorms-rain.svg",
        "141": "thunderstorms-night-overcast-snow.svg",
        "142": "thunderstorms-extreme-snow.svg",
        "210": "partly-cloudy-night-rain.svg",
        "211": "overcast-night-rain.svg",
        "212": "extreme-night-rain.svg",
        "220": "partly-cloudy-night-snow.svg",
        "221": "overcast-night-snow.svg",
        "222": "extreme-night-snow.svg",
        "230": "partly-cloudy-night-snow.svg",
        "231": "overcast-night-snow.svg",
        "232": "extreme-night-snow.svg",
        "235": "extreme-night-hail.svg"
    }
};